services:
  frontend:
    image: wordpress
    container_name: frontend
    ports:
      - "8088:80"
    restart: always
    depends_on:
      - frontend-db
    environment:
      WORDPRESS_DB_HOST: frontend-db:3306
      WORDPRESS_DB_USER: marcos
      WORDPRESS_DB_PASSWORD: Nacimi627267
      WORDPRESS_DB_NAME: frontend
    volumes:
      - frontend:/var/www/html

  frontend-db:
    image: mysql
    container_name: frontend-db
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Nacimi627267
      MYSQL_DATABASE: frontend
      MYSQL_USER: marcos
      MYSQL_PASSWORD: Nacimi627267
    volumes:
      - frontend-db:/var/lib/mysql

  admin-db:
    image: postgres
    container_name: admin-db
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: marcos
      POSTGRES_PASSWORD: Nacimi627267
      POSTGRES_DB: admin
    volumes:
      - admin-db:/var/lib/postgresql/data

  admin:
    build:
      dockerfile: ./admin/Dockerfile
    restart: always
    container_name: admin
    working_dir: /app
    volumes:
      - admin:/app
    networks:
      - admin
    ports:
      - "3000:3000"
    expose:
      - "3000"

  api:
    build:
      dockerfile: ./api/Dockerfile
    restart: always
    container_name: api
    working_dir: /app
    volumes:
      - .api:/app
    ports:
      - "2222:2222"
    depends_on:
      - admin-db
    environment:
      - NODE_ENV=development
    expose:
      - "8081"
    command: "npm start"

volumes:
  frontend:
  frontend-db:
  admin-db:
  admin:

networks:
  admin:
    driver: bridge
